-- 为现有业务表和字段补充数据字典注释，便于数据库运维、审计和排障。

COMMENT ON TABLE harness_runs IS 'Agent 运行主记录，保存一次任务的输入、输出、状态、预算及执行治理信息';
COMMENT ON COLUMN harness_runs.id IS '运行记录唯一标识';
COMMENT ON COLUMN harness_runs.tenant_id IS '租户唯一标识，用于多租户数据隔离';
COMMENT ON COLUMN harness_runs.user_id IS '发起运行的用户唯一标识';
COMMENT ON COLUMN harness_runs.title IS '运行标题';
COMMENT ON COLUMN harness_runs.model_name IS '本次运行使用的模型名称';
COMMENT ON COLUMN harness_runs.prompt_version IS '本次运行使用的提示词版本';
COMMENT ON COLUMN harness_runs.policy_version IS '本次运行使用的策略版本';
COMMENT ON COLUMN harness_runs.idempotency_key IS '客户端幂等键，用于避免同一租户重复创建运行';
COMMENT ON COLUMN harness_runs.permissions_snapshot IS '创建运行时固化的权限快照，保证执行期间权限语义稳定';
COMMENT ON COLUMN harness_runs.trace_id IS '贯穿本次运行及其异步消息的链路追踪标识';
COMMENT ON COLUMN harness_runs.input_data IS '运行输入内容';
COMMENT ON COLUMN harness_runs.output_data IS '运行成功后的最终输出内容';
COMMENT ON COLUMN harness_runs.error IS '运行失败、超时或取消时的错误信息';
COMMENT ON COLUMN harness_runs.status IS '运行状态，如排队、执行中、成功、失败、超时、取消或等待审批';
COMMENT ON COLUMN harness_runs.budget IS '本次运行允许使用的预算上限';
COMMENT ON COLUMN harness_runs.created_at IS '运行创建时间（带时区，应用按 UTC 读写）';
COMMENT ON COLUMN harness_runs.updated_at IS '运行记录最后更新时间';
COMMENT ON COLUMN harness_runs.started_at IS '运行开始执行时间';
COMMENT ON COLUMN harness_runs.finished_at IS '运行结束时间';
COMMENT ON COLUMN harness_runs.version IS 'JPA 乐观锁版本号';
COMMENT ON COLUMN harness_runs.worker_id IS '当前持有运行执行租约的 Worker 标识';
COMMENT ON COLUMN harness_runs.lease_until IS 'Worker 执行租约到期时间，过期后可被恢复器接管';
COMMENT ON COLUMN harness_runs.heartbeat_at IS 'Worker 最近一次刷新执行租约的时间';
COMMENT ON COLUMN harness_runs.agent_mode IS '是否启用 Agent 模式，由模型 Tool Call 动态追加步骤';
COMMENT ON COLUMN harness_runs.max_turns IS 'Agent 模式允许的最大模型轮数';
COMMENT ON COLUMN harness_runs.audit_event_count IS '本次运行审计链已封签事件数量';
COMMENT ON COLUMN harness_runs.audit_head_hash IS '本次运行审计链最新事件的哈希值';
COMMENT ON COLUMN harness_runs.audit_head_signature IS '本次运行审计链头的外部密钥 HMAC 签名';
COMMENT ON COLUMN harness_runs.conversation_id IS '所属聊天会话标识，独立运行时为空';
COMMENT ON COLUMN harness_runs.workspace_id IS '创建运行时绑定的本地工作区标识';
COMMENT ON COLUMN harness_runs.model_config_snapshot_id IS '创建运行时固化的模型供应商配置快照标识';

COMMENT ON TABLE harness_steps IS '运行步骤明细，记录模型调用、工具调用及其执行结果';
COMMENT ON COLUMN harness_steps.id IS '步骤记录唯一标识';
COMMENT ON COLUMN harness_steps.span_id IS '步骤对应的链路追踪 Span 标识';
COMMENT ON COLUMN harness_steps.run_id IS '所属运行标识';
COMMENT ON COLUMN harness_steps.step_sequence IS '步骤在运行中的顺序号';
COMMENT ON COLUMN harness_steps.type IS '步骤类型，如模型调用或工具调用';
COMMENT ON COLUMN harness_steps.status IS '步骤状态，如排队、执行中、成功、失败、拒绝、取消、超时或等待审批';
COMMENT ON COLUMN harness_steps.name IS '步骤名称，通常为模型或工具名称';
COMMENT ON COLUMN harness_steps.input_data IS '步骤输入参数或提示内容';
COMMENT ON COLUMN harness_steps.output_data IS '步骤输出结果或模型响应';
COMMENT ON COLUMN harness_steps.error IS '步骤失败、拒绝或超时时的错误信息';
COMMENT ON COLUMN harness_steps.attempt IS '步骤实际执行尝试次数';
COMMENT ON COLUMN harness_steps.input_tokens IS '本步骤消耗的输入 Token 数量';
COMMENT ON COLUMN harness_steps.output_tokens IS '本步骤产生的输出 Token 数量';
COMMENT ON COLUMN harness_steps.approval_granted IS '是否已获得人工审批授权';
COMMENT ON COLUMN harness_steps.started_at IS '步骤开始执行时间';
COMMENT ON COLUMN harness_steps.finished_at IS '步骤结束时间';
COMMENT ON COLUMN harness_steps.duration_ms IS '步骤执行耗时（毫秒）';
COMMENT ON COLUMN harness_steps.cost IS '步骤产生的模型或工具成本';
COMMENT ON COLUMN harness_steps.replay_source_step_id IS '复用结果时所引用的源步骤标识，避免重复执行工具';

COMMENT ON TABLE harness_audit_events IS '运行审计事件，记录任务、步骤及治理操作的可追溯事件流';
COMMENT ON COLUMN harness_audit_events.id IS '审计事件唯一标识';
COMMENT ON COLUMN harness_audit_events.run_id IS '关联的运行标识';
COMMENT ON COLUMN harness_audit_events.step_id IS '关联的步骤标识';
COMMENT ON COLUMN harness_audit_events.tenant_id IS '租户唯一标识';
COMMENT ON COLUMN harness_audit_events.actor_id IS '触发事件的用户、服务或 Worker 标识';
COMMENT ON COLUMN harness_audit_events.trace_id IS '事件所属链路追踪标识';
COMMENT ON COLUMN harness_audit_events.event_type IS '审计事件类型';
COMMENT ON COLUMN harness_audit_events.message IS '审计事件描述，写入前会进行脱敏';
COMMENT ON COLUMN harness_audit_events.metadata IS '审计事件附加元数据，写入前会进行脱敏';
COMMENT ON COLUMN harness_audit_events.created_at IS '审计事件创建时间';
COMMENT ON COLUMN harness_audit_events.integrity_sequence IS '事件在运行审计链中的连续序号';
COMMENT ON COLUMN harness_audit_events.previous_hash IS '前一条审计事件的哈希值';
COMMENT ON COLUMN harness_audit_events.integrity_hash IS '当前审计事件内容的哈希值';

COMMENT ON TABLE harness_context_documents IS '租户知识文档，为上下文构建提供可授权检索的长期资料';
COMMENT ON COLUMN harness_context_documents.id IS '知识文档唯一标识';
COMMENT ON COLUMN harness_context_documents.tenant_id IS '所属租户标识';
COMMENT ON COLUMN harness_context_documents.owner_user_id IS '文档所有者用户标识';
COMMENT ON COLUMN harness_context_documents.title IS '文档标题';
COMMENT ON COLUMN harness_context_documents.content IS '文档正文内容';
COMMENT ON COLUMN harness_context_documents.sensitivity IS '文档敏感级别';
COMMENT ON COLUMN harness_context_documents.allowed_users IS '允许访问文档的用户标识列表，逗号分隔；为空表示租户内可见';
COMMENT ON COLUMN harness_context_documents.created_at IS '文档创建时间';
COMMENT ON COLUMN harness_context_documents.updated_at IS '文档最后更新时间';
COMMENT ON COLUMN harness_context_documents.deleted_at IS '文档软删除时间，未删除时为空';

COMMENT ON TABLE harness_context_memories IS '用户上下文记忆，保存可在后续运行中复用的个性化信息';
COMMENT ON COLUMN harness_context_memories.id IS '记忆条目唯一标识';
COMMENT ON COLUMN harness_context_memories.tenant_id IS '所属租户标识';
COMMENT ON COLUMN harness_context_memories.user_id IS '记忆所属用户标识';
COMMENT ON COLUMN harness_context_memories.memory_type IS '记忆类型';
COMMENT ON COLUMN harness_context_memories.content IS '记忆内容';
COMMENT ON COLUMN harness_context_memories.source_run_id IS '产生该记忆的源运行标识';
COMMENT ON COLUMN harness_context_memories.expires_at IS '记忆失效时间，为空表示不过期';
COMMENT ON COLUMN harness_context_memories.created_at IS '记忆创建时间';
COMMENT ON COLUMN harness_context_memories.deleted_at IS '记忆软删除时间，未删除时为空';

COMMENT ON TABLE harness_evaluation_reports IS '评测报告汇总，记录一组评测用例的模型表现和版本信息';
COMMENT ON COLUMN harness_evaluation_reports.id IS '评测报告唯一标识';
COMMENT ON COLUMN harness_evaluation_reports.tenant_id IS '所属租户标识';
COMMENT ON COLUMN harness_evaluation_reports.name IS '评测报告名称';
COMMENT ON COLUMN harness_evaluation_reports.model_name IS '评测使用的模型名称';
COMMENT ON COLUMN harness_evaluation_reports.prompt_version IS '评测使用的提示词版本';
COMMENT ON COLUMN harness_evaluation_reports.policy_version IS '评测使用的策略版本';
COMMENT ON COLUMN harness_evaluation_reports.total_cases IS '评测用例总数';
COMMENT ON COLUMN harness_evaluation_reports.passed_cases IS '通过的评测用例数';
COMMENT ON COLUMN harness_evaluation_reports.failed_cases IS '失败的评测用例数';
COMMENT ON COLUMN harness_evaluation_reports.success_rate IS '评测通过率';
COMMENT ON COLUMN harness_evaluation_reports.details IS '评测明细或结构化结果';
COMMENT ON COLUMN harness_evaluation_reports.created_at IS '评测报告创建时间';

COMMENT ON TABLE harness_outbox_events IS '事务 Outbox 事件，保证运行状态变更与异步执行命令可靠投递';
COMMENT ON COLUMN harness_outbox_events.id IS 'Outbox 事件唯一标识';
COMMENT ON COLUMN harness_outbox_events.run_id IS '关联的运行标识';
COMMENT ON COLUMN harness_outbox_events.tenant_id IS '所属租户标识';
COMMENT ON COLUMN harness_outbox_events.trace_id IS '事件所属链路追踪标识';
COMMENT ON COLUMN harness_outbox_events.command IS '待投递的执行命令类型';
COMMENT ON COLUMN harness_outbox_events.payload IS '命令消息载荷';
COMMENT ON COLUMN harness_outbox_events.status IS '投递状态，如待处理、发布中、已发布或失败';
COMMENT ON COLUMN harness_outbox_events.attempts IS '已尝试发布次数';
COMMENT ON COLUMN harness_outbox_events.next_attempt_at IS '下一次允许发布的时间';
COMMENT ON COLUMN harness_outbox_events.published_at IS '事件成功发布的时间';
COMMENT ON COLUMN harness_outbox_events.last_error IS '最近一次发布失败的错误信息';
COMMENT ON COLUMN harness_outbox_events.claimed_by IS '当前持有发布租约的 Relay 实例标识';
COMMENT ON COLUMN harness_outbox_events.claim_until IS '发布租约到期时间，过期后可被其他实例接管';
COMMENT ON COLUMN harness_outbox_events.created_at IS 'Outbox 事件创建时间';

COMMENT ON TABLE harness_tenant_policies IS '租户级运行资源策略，保存比平台硬上限更严格的租户限制';
COMMENT ON COLUMN harness_tenant_policies.tenant_id IS '租户唯一标识';
COMMENT ON COLUMN harness_tenant_policies.max_active_runs IS '租户同时处于活动状态的运行数上限';
COMMENT ON COLUMN harness_tenant_policies.max_steps_per_run IS '单次运行允许创建的步骤数上限';
COMMENT ON COLUMN harness_tenant_policies.max_input_length IS '单次运行输入内容的长度上限';
COMMENT ON COLUMN harness_tenant_policies.max_budget IS '单次运行允许使用的预算上限';
COMMENT ON COLUMN harness_tenant_policies.max_creates_per_minute IS '租户每分钟允许创建运行的次数上限';
COMMENT ON COLUMN harness_tenant_policies.allowed_tools IS '租户允许使用的工具名称白名单，逗号分隔；为空表示允许所有已注册工具';
COMMENT ON COLUMN harness_tenant_policies.created_at IS '租户策略创建时间';
COMMENT ON COLUMN harness_tenant_policies.updated_at IS '租户策略最后更新时间';
COMMENT ON COLUMN harness_tenant_policies.version IS 'JPA 乐观锁版本号';

COMMENT ON TABLE harness_tenant_policy_audits IS '租户资源策略变更审计记录，用于追溯配置创建、修改和恢复';
COMMENT ON COLUMN harness_tenant_policy_audits.id IS '策略审计记录唯一标识';
COMMENT ON COLUMN harness_tenant_policy_audits.tenant_id IS '被变更策略所属的租户标识';
COMMENT ON COLUMN harness_tenant_policy_audits.actor_id IS '执行策略变更的用户或服务标识';
COMMENT ON COLUMN harness_tenant_policy_audits.event_type IS '策略变更事件类型';
COMMENT ON COLUMN harness_tenant_policy_audits.details IS '策略变更详情';
COMMENT ON COLUMN harness_tenant_policy_audits.created_at IS '策略审计记录创建时间';

COMMENT ON TABLE harness_api_keys IS 'API Key 凭证，保存密钥摘要及生命周期信息，不保存密钥明文';
COMMENT ON COLUMN harness_api_keys.id IS 'API Key 凭证唯一标识';
COMMENT ON COLUMN harness_api_keys.key_hash IS 'API Key 的 SHA-256 摘要，用于请求校验';
COMMENT ON COLUMN harness_api_keys.key_prefix IS 'API Key 前缀，用于控制台展示和人工识别';
COMMENT ON COLUMN harness_api_keys.tenant_id IS '所属租户标识';
COMMENT ON COLUMN harness_api_keys.user_id IS 'API Key 所属用户标识';
COMMENT ON COLUMN harness_api_keys.permissions IS 'API Key 权限集合的序列化内容';
COMMENT ON COLUMN harness_api_keys.status IS 'API Key 状态，如有效或已撤销';
COMMENT ON COLUMN harness_api_keys.expires_at IS 'API Key 过期时间，为空表示不过期';
COMMENT ON COLUMN harness_api_keys.created_at IS 'API Key 创建时间';
COMMENT ON COLUMN harness_api_keys.revoked_at IS 'API Key 撤销时间，未撤销时为空';
COMMENT ON COLUMN harness_api_keys.revoked_by IS '撤销 API Key 的操作者标识';
COMMENT ON COLUMN harness_api_keys.version IS 'JPA 乐观锁版本号';

COMMENT ON TABLE harness_api_key_audits IS 'API Key 生命周期审计记录，记录创建和撤销等管理操作';
COMMENT ON COLUMN harness_api_key_audits.id IS 'API Key 审计记录唯一标识';
COMMENT ON COLUMN harness_api_key_audits.key_id IS '关联的 API Key 凭证标识';
COMMENT ON COLUMN harness_api_key_audits.tenant_id IS '所属租户标识';
COMMENT ON COLUMN harness_api_key_audits.actor_id IS '执行 API Key 操作的用户或服务标识';
COMMENT ON COLUMN harness_api_key_audits.event_type IS 'API Key 生命周期事件类型';
COMMENT ON COLUMN harness_api_key_audits.details IS '事件详情，不包含密钥明文';
COMMENT ON COLUMN harness_api_key_audits.created_at IS 'API Key 审计记录创建时间';

COMMENT ON TABLE harness_conversations IS '聊天会话主记录，组织用户与 Agent 的连续多轮对话';
COMMENT ON COLUMN harness_conversations.id IS '聊天会话唯一标识';
COMMENT ON COLUMN harness_conversations.tenant_id IS '所属租户标识';
COMMENT ON COLUMN harness_conversations.user_id IS '会话所属用户标识';
COMMENT ON COLUMN harness_conversations.title IS '会话标题，可由首条消息自动生成或由用户重命名';
COMMENT ON COLUMN harness_conversations.created_at IS '会话创建时间';
COMMENT ON COLUMN harness_conversations.updated_at IS '会话最后活跃或修改时间';
COMMENT ON COLUMN harness_conversations.workspace_id IS '会话绑定的本地工作区标识';

COMMENT ON TABLE harness_conversation_messages IS '聊天会话消息明细，保存用户消息和与运行关联的 Agent 消息';
COMMENT ON COLUMN harness_conversation_messages.id IS '会话消息唯一标识';
COMMENT ON COLUMN harness_conversation_messages.conversation_id IS '所属聊天会话标识';
COMMENT ON COLUMN harness_conversation_messages.run_id IS '关联的 Agent 运行标识，用户消息通常为空';
COMMENT ON COLUMN harness_conversation_messages.tenant_id IS '所属租户标识';
COMMENT ON COLUMN harness_conversation_messages.user_id IS '消息所属用户标识';
COMMENT ON COLUMN harness_conversation_messages.role IS '消息角色，如用户或助手';
COMMENT ON COLUMN harness_conversation_messages.status IS '消息状态，如待处理、完成、失败或取消';
COMMENT ON COLUMN harness_conversation_messages.message_sequence IS '消息在会话中的顺序号';
COMMENT ON COLUMN harness_conversation_messages.content IS '消息正文或生成中的内容快照';
COMMENT ON COLUMN harness_conversation_messages.created_at IS '消息创建时间';
COMMENT ON COLUMN harness_conversation_messages.updated_at IS '消息最后更新时间';

COMMENT ON TABLE harness_conversation_attachments IS '聊天附件元数据，正文保存在受控工作区，表内保存归属和相对路径';
COMMENT ON COLUMN harness_conversation_attachments.id IS '附件记录唯一标识';
COMMENT ON COLUMN harness_conversation_attachments.conversation_id IS '所属聊天会话标识';
COMMENT ON COLUMN harness_conversation_attachments.message_id IS '绑定的用户消息标识，未绑定时为空';
COMMENT ON COLUMN harness_conversation_attachments.tenant_id IS '所属租户标识';
COMMENT ON COLUMN harness_conversation_attachments.user_id IS '上传附件的用户标识';
COMMENT ON COLUMN harness_conversation_attachments.original_name IS '用户上传时的原始文件名或目录名';
COMMENT ON COLUMN harness_conversation_attachments.workspace_path IS '附件在受控工作区中的相对路径';
COMMENT ON COLUMN harness_conversation_attachments.media_type IS '附件媒体类型或 MIME 类型';
COMMENT ON COLUMN harness_conversation_attachments.size_bytes IS '附件大小（字节）';
COMMENT ON COLUMN harness_conversation_attachments.created_at IS '附件元数据创建时间';
COMMENT ON COLUMN harness_conversation_attachments.directory IS '是否代表一个目录附件';
COMMENT ON COLUMN harness_conversation_attachments.file_count IS '目录附件包含的文件数量，普通文件为 1';

COMMENT ON TABLE harness_local_workspaces IS '用户授权给本地 Agent 使用的工作区，根目录仅以密文持久化';
COMMENT ON COLUMN harness_local_workspaces.id IS '本地工作区唯一标识';
COMMENT ON COLUMN harness_local_workspaces.tenant_id IS '所属租户标识';
COMMENT ON COLUMN harness_local_workspaces.user_id IS '授权工作区的用户标识';
COMMENT ON COLUMN harness_local_workspaces.display_name IS '工作区展示名称';
COMMENT ON COLUMN harness_local_workspaces.root_path_ciphertext IS '工作区根目录绝对路径的加密密文';
COMMENT ON COLUMN harness_local_workspaces.created_at IS '工作区授权记录创建时间';
COMMENT ON COLUMN harness_local_workspaces.updated_at IS '工作区最后使用或更新时间';
COMMENT ON COLUMN harness_local_workspaces.version IS 'JPA 乐观锁版本号';

COMMENT ON TABLE harness_conversation_contexts IS '聊天会话上下文压缩快照，保存历史消息摘要以控制模型上下文长度';
COMMENT ON COLUMN harness_conversation_contexts.conversation_id IS '会话标识，同时作为上下文快照主键';
COMMENT ON COLUMN harness_conversation_contexts.summary IS '已压缩历史消息的摘要内容';
COMMENT ON COLUMN harness_conversation_contexts.compacted_through_sequence IS '摘要已覆盖到的最大消息顺序号';
COMMENT ON COLUMN harness_conversation_contexts.summary_version IS '上下文摘要版本号';
COMMENT ON COLUMN harness_conversation_contexts.created_at IS '上下文快照创建时间';
COMMENT ON COLUMN harness_conversation_contexts.updated_at IS '上下文快照最后更新时间';

COMMENT ON TABLE harness_model_provider_configs IS '租户用户的模型供应商配置，API Key 仅保存 AES-GCM 密文';
COMMENT ON COLUMN harness_model_provider_configs.id IS '模型供应商配置唯一标识';
COMMENT ON COLUMN harness_model_provider_configs.tenant_id IS '所属租户标识';
COMMENT ON COLUMN harness_model_provider_configs.user_id IS '配置所属用户标识';
COMMENT ON COLUMN harness_model_provider_configs.enabled IS '是否启用该模型供应商配置';
COMMENT ON COLUMN harness_model_provider_configs.base_url IS 'OpenAI 兼容模型供应商的接口基础地址';
COMMENT ON COLUMN harness_model_provider_configs.model_name IS '供应商侧模型名称';
COMMENT ON COLUMN harness_model_provider_configs.api_key_ciphertext IS 'API Key 的 AES-GCM 加密密文';
COMMENT ON COLUMN harness_model_provider_configs.api_key_hint IS '用于展示的 API Key 脱敏提示，不包含完整密钥';
COMMENT ON COLUMN harness_model_provider_configs.created_at IS '模型供应商配置创建时间';
COMMENT ON COLUMN harness_model_provider_configs.updated_at IS '模型供应商配置最后更新时间';
COMMENT ON COLUMN harness_model_provider_configs.version IS 'JPA 乐观锁版本号';
COMMENT ON COLUMN harness_model_provider_configs.active_snapshot_id IS '当前生效的模型配置快照标识';

COMMENT ON TABLE harness_model_provider_config_snapshots IS '运行使用的模型供应商配置快照，创建运行时固化以避免配置变更影响已排队任务';
COMMENT ON COLUMN harness_model_provider_config_snapshots.id IS '模型配置快照唯一标识';
COMMENT ON COLUMN harness_model_provider_config_snapshots.tenant_id IS '所属租户标识';
COMMENT ON COLUMN harness_model_provider_config_snapshots.user_id IS '快照所属用户标识';
COMMENT ON COLUMN harness_model_provider_config_snapshots.enabled IS '快照生成时配置是否启用';
COMMENT ON COLUMN harness_model_provider_config_snapshots.base_url IS '快照中的模型供应商接口基础地址';
COMMENT ON COLUMN harness_model_provider_config_snapshots.model_name IS '快照中的供应商侧模型名称';
COMMENT ON COLUMN harness_model_provider_config_snapshots.api_key_ciphertext IS '快照中的 API Key AES-GCM 加密密文';
COMMENT ON COLUMN harness_model_provider_config_snapshots.created_at IS '模型配置快照创建时间';
